FROM fmu_base

COPY ./sim.zip /src/generic/generic.fmu

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Run main task
CMD "python .\generic\main.py"
